source 'https://rubygems.org'
ruby '3.4.5'

gem 'attr_encrypted'
gem 'aweber'
gem 'aws-sdk-s3'
gem 'base64'
gem 'bcrypt', '~> 3.1.7'
gem 'bigdecimal'
gem 'bootsnap', require: false
gem 'browser-timezone-rails'
gem 'fiddle'
gem 'font-awesome-rails'
gem 'httparty'
gem 'jquery-rails'
gem 'kaminari'
gem 'mailboxer'
gem 'mailgun-ruby'
gem 'mutex_m'
gem 'mysql2', '~> 0.5.3'
gem 'net-http'
gem 'oauth'
gem 'ostruct'
# gem 'pg' # I need to understand which database is used.
gem 'premailer-rails'
gem 'psych', '~> 3.0'
gem 'puma'
gem 'rack-cors'
gem 'rails', '~> 8.0'
gem 'ruby2_keywords', '~> 0.0.5'
gem 'sass-rails'
gem 'sentry-rails'
gem 'sentry-ruby'
gem 'sidekiq'
gem 'sidekiq-cron'
gem 'stackprof'
gem 'stripe', '~> 5.21.0'
gem 'uglifier'

group :development, :test do
  gem 'better_errors'
  gem 'byebug'
  gem 'database_cleaner'
  gem 'factory_bot_rails'
  gem 'faker'
  gem 'pry-rails'
  gem 'rails_best_practices'
  gem 'rspec-rails'
  gem 'rubocop'
  gem 'shoulda-matchers'
end

# apple m1 may need to run gem install sassc -- --disable-march-tune-native
# took out of Gemfile.lock as a result
