development:
  adapter: async

test:
  adapter: async

container:
  adapter: redis
  url: <%= ENV['REDIS_URL'] %>
  channel_prefix: bookclicker_container

heroku:
  adapter: redis
  url: <%= ENV['REDIS_URL'] %>
  channel_prefix: bookclicker_heroku

production:
  adapter: redis
  url: <%= ENV['REDIS_URL'] %>
  channel_prefix: bookclicker_production
