retrieve_seller_email_campaigns_job:
  cron: "41 10,12,14 * * *"
  class: "RetrieveSellerEmailCampaignsJob"
  description: "Retrieve Seller Email Campaigns Job"

process_list_subscriptions_job:
  cron: "15 * * * *"
  class: "ProcessListSubscriptionsJob"
  description: "Process List Subscriptions Job"

get_assistant_subscription_statuses_job:
  cron: "28 4 * * *"
  class: "GetAssistantSubscriptionStatusesJob"
  description: "Get Assistant Subscription Statuses Job"

mailing_lists_updator_job:
  cron: "0 5 * * *"
  class: "MailingListsUpdatorJob"
  args: ["perform_for_all"]
  description: "Update Mailing Lists for All Users"

remove_obsolete_lists_job:
  cron: "18 18 * * *"
  class: "RemoveObsoleteListsJob"
  description: "Remove Obsolete Lists Job"

issue_requested_refunds_job:
  cron: "3 6 * * *"
  class: "IssueRequestedRefundsJob"
  description: "Issue Requested Refunds Job"

message_notifications_job:
  cron: "2,12,22,32,42,52 * * * *"
  class: "MessageNotificationsJob"
  description: "Message Notifications Job"

clear_log_files_job:
  cron: "25 1 3 * *"
  class: "ClearLogFiles"
  description: "Clear Log Files Job"
